version: '3.8'

services:
  ecommerce_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${STORE_CODE}_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "127.0.0.1:${APP_PORT}:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - ecommerce_db
    networks:
      - app_network

  ecommerce_db:
    image: mysql:8.0
    container_name: ${STORE_CODE}_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-shopinmy}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-shopinmy_user}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
