version: '3.8'

services:
  ecommerce_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${STORE_CODE}_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - ecommerce_db
    networks:
      - ${STORE_CODE}_network

  ecommerce_queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${STORE_CODE}_queue
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./:/var/www/html
    depends_on:
      - ecommerce_db
      - ecommerce_app
    networks:
      - ${STORE_CODE}_network

  ecommerce_web:
    image: nginx:alpine
    container_name: ${STORE_CODE}_web
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/production.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ecommerce_app
    networks:
      - ${STORE_CODE}_network
      - nginx-proxy

  ecommerce_db:
    image: mysql:8.0
    container_name: ${STORE_CODE}_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-shopinmy}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-shopinmy_user}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ${STORE_CODE}_network

volumes:
  db_data:

networks:
  ${STORE_CODE}_network:
    driver: bridge
  nginx-proxy:
    external: true
